Resources:
  DynamoTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: dealDesc
          AttributeType: S
        - AttributeName: notes
          AttributeType: S
        - AttributeName: lat
          AttributeType: N
        - AttributeName: lng
          AttributeType: N
        - AttributeName: address
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      TableName: discounts
